<a href="https://colab.research.google.com/github/Debanil1996/Python-AI-Practice/blob/master/NumpyPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x=np.array([[1,1],[2,2]])


In [2]:
x.sum(axis=0)

array([3, 3])

In [3]:
x.sum(axis=1) #Row wise sum

array([2, 4])

In [4]:
arr = np.zeros([10,10])
arr[2][2]=1
np.any(arr != 0)

True

In [5]:
x=np.array([1,2,3,4,5])
y=np.array([[1,3,4,5],[6,7,8,9]])
x.mean()

3.0

In [6]:
f1=np.array([1,2,3,4,5])
f2=np.array([[1,5,7,8],[2,6,9,12]])
f1.mean()

3.0

In [7]:
np.median(f1)

3.0

In [8]:
np.median(f2,axis=0)

array([ 1.5,  5.5,  8. , 10. ])

In [9]:
datas = np.loadtxt('populations.txt')
datas

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [10]:
year,hares,lyncs,carrots=datas.T
print(hares)

[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700.]


In [11]:
populations=datas[:,:1]


In [12]:
populations.std(axis=0)

array([6.05530071])

In [13]:
np.argmax(populations,axis=1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
a1= np.tile(np.arange(0,40,10),(3,1))
a1=a1.T
print(a1)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [15]:
b1= a1.ravel()
print(b1)

[ 0  0  0 10 10 10 20 20 20 30 30 30]


In [16]:
ar=np.arange(5)
ar.resize(8,)
print(ar)

[0 1 2 3 4 0 0 0]


In [19]:
# br=ar
findx = np.array([10,9,13,8,6,7,5,4,3,1,2,12])
jt=np.argsort(findx)
print(jt)

[ 9 10  8  7  6  4  5  3  1  0 11  2]
